### ISSUE TITLE
Theme "stack" imposes deadlock if used with plugin "readitlater"

### ISSUE THREAD

**Issue by Gnlfz007** [RolandTi/shaarli-stack#3]
If plugin "read it later" is enabled AND "read it later" is selected AND the list of marked entries becomes empty, THEN there is no control available do disable the read-it-later mode. No entries can be shown anymore. The related toggle button provided by the default theme is missing.

Workaround: Logout --> Login.

**Comment by RolandTi** [comment]
First, thanks for letting me now about this fabulous plugin, I was thinking it's was related to the Pocket app.

This is happening because I use the condition to have more than one article to display the navbar so I have a clean layout when i'ts display one article.


I will work on that for the next version, but if you want to fix it now : 
- open the file in **_inc/linklist.paging.html**
- remove the first line `{if="count($links)>1"}`
- remove the last line ` {/if}`

<img width="1863" alt="Capture d’écran 2023-12-04 à 15 39 33" src="https://github.com/RolandTi/shaarli-stack/assets/28786873/50eeef50-0682-4e07-8e21-a69268b8ff85">

**Comment by Gnlfz007** [comment]
Yes, this workaround keeps the link "Mark as Read" on the bottom of the list and clicking it again toggles back to the full view.

Btw; filtering for unread bookmarks clicking a link named "Mark as Read" is not really intuitive. There should be a control button "Filter ReaditLater bookmarks" as provided by the default theme. The related updates to the default plugin should probably be merged into the stack plugin. Not quite sure of course.

Another simple WA without code change is just to keep one entry (a note)  tagged "read it later" and never mark it read.

Thanks for the stack plugin anyway; it is useful as is. The default theme terribly hurts the eyes.

**Comment by RolandTi** [comment]
Hello ! I'm putting the new version online today. I added the plugin to the filter list. Hope you'll enjoy !
